### ISSUE TITLE
IndexOutOfRangeException on GetTasteForGift

### ISSUE THREAD

**Issue by Roumaan** [JoXW100/GiftTasteHelper#1]
Hi, it's me again, thank you for the special update! 😄  The error moved to another function. Here is the log. 
[smapi.io parsed](https://smapi.io/log/768cfcadc3d64d018deedc9a9e8ff2d8)
[SMAPI-latest.txt](https://github.com/JoXW100/GiftTasteHelper/files/14740905/SMAPI-latest.txt)

**Comment by Roumaan** [comment]
Tried to build and run this myself with added debug output at the beginning of the function, but the error seems to have moved further down GetTasteForGift to line 229 (though there are even more mods since last time lol) and seems to break on NPC: Universal_Disliked; ItemId: 74.
![VS screenshot](https://github.com/JoXW100/GiftTasteHelper/assets/16963703/c5c6a6ad-0206-4f46-a1e4-6aa860c322ed)
[log on smapi.io](https://smapi.io/log/012730fc438e404b9349245ad911011c?Levels=debug~error~critical&Page=4&PerPage=1000)

**Comment by Roumaan** [comment]
After disabling the mods installed or updated since yesterday the error didn't change at all as far as I can tell, the save hasn't progressed since yesterday either. So the change in error after building the mod myself is probably caused by the changes in the repo

**Comment by Roumaan** [comment]
Hmm, the dll in the new published version of the mod seems to have been built three hours ago and the error is back at line 141

**Comment by JoXW100** [comment]
@Roumaan, Looking at the screenshot it seems like the error occurs when `npcName` is  "Universal_Disliked" , is this caused by some other mod? The "correct" name should be "Universal_Dislike". I am having trouble finding the cause of this bug myself as i haven't been able to reproduce the error. 

I will push an update that should catch any `IndexOutOfRangeExpeption` at line 229 and 141. I will attach a debug version, let me know if it works for you:

[GiftTasteHelper 1.0.0.zip](https://github.com/JoXW100/GiftTasteHelper/files/14743646/GiftTasteHelper.1.0.0.zip)

**Comment by Roumaan** [comment]
Thank you! I managed to isolate responsible mod - Arrbyte's Zebrafinches which attempts to add "Arrbyte.Zebrafinches_NestingMaterial" to "Universal_Disliked", not sure why it showed up as Prismatic shard in Visual Studio though(that's for Arrbyte to figure out of course). And most importantly the new GiftTasteHelper version indeed works despite the problematic mod. Sorry for bothering you so much with this unrelated to this mod problem and thank you for helping me regardless 🙏
